### ISSUE TITLE
Which folder to write to

### ISSUE THREAD

**Issue by olleharstedt** [reportico-web/limesurvey-reportico#2]
You should write to tmp/ or runtime/, not in the project/ folder in your plugin.

> Error cant create project area /var/www/lime25/limesurvey/plugins/Reportico/projects

**Comment by reportico-web** [comment]
Hi there .. thanks for the tip .. I have changed code to use following to get the runtime path for writing :-: 

`Yii::app()->getRuntimePath()."/reportico/projects";`

I hope that's ok

**Comment by olleharstedt** [comment]
Sounds good, just don't forget to test it. :)
